import { and, asc, desc, eq, inArray, isNotNull, isNull, sql } from 'drizzle-orm';
import { schema } from '@/db';
import { withOrg } from '@/db/tenant';
import { AccessError, InvalidRequestError } from './errors';
import { isUuid } from '@/core/validation';
import type { OrgScope } from './monitors';

const { incidents, incidentUpdates, users } = schema;

/**
 * Lesson 2.3 (🟡): post an update on an incident of this org (404 for any
 * other). Its text becomes searchable at once: the tsvector column is
 * generated by Postgres in the same INSERT.
 */
export async function addIncidentUpdate(ctx: OrgScope & { userId: string }, incidentId: string, body: string) {
  if (!isUuid(incidentId)) throw new AccessError('not_found');
  return withOrg(ctx.orgId, async (tx) => {
    const [incident] = await tx
      .select({ id: incidents.id })
      .from(incidents)
      .where(and(eq(incidents.organizationId, ctx.orgId), eq(incidents.id, incidentId)));
    if (!incident) throw new AccessError('not_found');
    const [row] = await tx.insert(incidentUpdates).values({ organizationId: ctx.orgId, incidentId, authorId: ctx.userId, body }).returning();
    return row;
  });
}

/** The updates of some incidents of this org, oldest first, with the author's name. */
export async function listIncidentUpdates({ orgId }: OrgScope, incidentIds: string[]) {
  if (incidentIds.length === 0) return [];
  return withOrg(orgId, (tx) =>
    tx
      .select({
        id: incidentUpdates.id,
        incidentId: incidentUpdates.incidentId,
        body: incidentUpdates.body,
        createdAt: incidentUpdates.createdAt,
        authorName: users.name,
      })
      .from(incidentUpdates)
      .leftJoin(users, eq(users.id, incidentUpdates.authorId))
      .where(and(eq(incidentUpdates.organizationId, orgId), inArray(incidentUpdates.incidentId, incidentIds)))
      .orderBy(asc(incidentUpdates.createdAt)),
  );
}

/**
 * Lesson 5.2 (🟢): one page of this org's incidents for the public API,
 * newest first, with the same cursor pagination as listMonitorsPage().
 */
export async function listIncidentsPage(
  { orgId }: OrgScope,
  opts: { limit: number; startingAfter?: string; status?: 'open' | 'resolved'; monitorId?: string },
) {
  return withOrg(orgId, async (tx) => {
    const filters = [eq(incidents.organizationId, orgId)];
    if (opts.status === 'open') filters.push(isNull(incidents.resolvedAt));
    if (opts.status === 'resolved') filters.push(isNotNull(incidents.resolvedAt));
    if (opts.monitorId) filters.push(eq(incidents.monitorId, opts.monitorId));
    if (opts.startingAfter) {
      const [cursor] = await tx.select({ id: incidents.id }).from(incidents).where(and(eq(incidents.organizationId, orgId), eq(incidents.id, opts.startingAfter)));
      if (!cursor) throw new InvalidRequestError('invalid_cursor', 'starting_after is not an incident of this organization.');
      filters.push(sql`(${incidents.createdAt}, ${incidents.id}) < (select i.created_at, i.id from incidents i where i.id = ${cursor.id})`);
    }
    const rows = await tx
      .select()
      .from(incidents)
      .where(and(...filters))
      .orderBy(desc(incidents.createdAt), desc(incidents.id))
      .limit(opts.limit + 1);
    return { rows: rows.slice(0, opts.limit), hasMore: rows.length > opts.limit };
  });
}

/** One incident of this org, or null (another org's id is null too: 404). */
export async function getIncident({ orgId }: OrgScope, incidentId: string) {
  if (!isUuid(incidentId)) return null;
  const [row] = await withOrg(orgId, (tx) => tx.select().from(incidents).where(and(eq(incidents.organizationId, orgId), eq(incidents.id, incidentId))));
  return row ?? null;
}
