import { and, asc, eq, inArray } from 'drizzle-orm';
import { schema } from '@/db';
import { withOrg } from '@/db/tenant';
import { AccessError } from './errors';
import { isUuid } from '@/core/validation';
import type { OrgScope } from './monitors';

const { incidents, incidentUpdates, users } = schema;

/**
 * Lesson 2.3 (🟡): post an update on an incident of this org (404 for any
 * other). Its text becomes searchable at once: the tsvector column is
 * generated by Postgres in the same INSERT.
 */
export async function addIncidentUpdate(ctx: OrgScope & { userId: string }, incidentId: string, body: string) {
  if (!isUuid(incidentId)) throw new AccessError('not_found');
  return withOrg(ctx.orgId, async (tx) => {
    const [incident] = await tx
      .select({ id: incidents.id })
      .from(incidents)
      .where(and(eq(incidents.organizationId, ctx.orgId), eq(incidents.id, incidentId)));
    if (!incident) throw new AccessError('not_found');
    const [row] = await tx.insert(incidentUpdates).values({ organizationId: ctx.orgId, incidentId, authorId: ctx.userId, body }).returning();
    return row;
  });
}

/** The updates of some incidents of this org, oldest first, with the author's name. */
export async function listIncidentUpdates({ orgId }: OrgScope, incidentIds: string[]) {
  if (incidentIds.length === 0) return [];
  return withOrg(orgId, (tx) =>
    tx
      .select({
        id: incidentUpdates.id,
        incidentId: incidentUpdates.incidentId,
        body: incidentUpdates.body,
        createdAt: incidentUpdates.createdAt,
        authorName: users.name,
      })
      .from(incidentUpdates)
      .leftJoin(users, eq(users.id, incidentUpdates.authorId))
      .where(and(eq(incidentUpdates.organizationId, orgId), inArray(incidentUpdates.incidentId, incidentIds)))
      .orderBy(asc(incidentUpdates.createdAt)),
  );
}
