-- Lesson 2.1: created_at/updated_at on every table Beacon owns, and the indexes
-- behind the dashboard query. Generated by drizzle-kit, annotated by hand.
--
-- Why ADD COLUMN is safe on a big, busy table: since Postgres 11, ADD COLUMN
-- with a non-volatile default such as now() only records the default in the
-- catalog (now() is evaluated once, for the whole statement). A volatile
-- default such as clock_timestamp() or gen_random_uuid() would rewrite every
-- row under an exclusive lock.
ALTER TABLE "incidents" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "incidents" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "invitations" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "memberships" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "monitors" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
-- Backfill: the new columns say "now" for existing rows. Give them the best
-- time we actually know.
UPDATE "incidents" SET "created_at" = "opened_at", "updated_at" = coalesce("resolved_at", "opened_at");--> statement-breakpoint
UPDATE "monitors" SET "updated_at" = "created_at";--> statement-breakpoint
UPDATE "organizations" SET "updated_at" = "created_at";--> statement-breakpoint
UPDATE "memberships" SET "updated_at" = "created_at";--> statement-breakpoint
UPDATE "invitations" SET "updated_at" = "sent_at";--> statement-breakpoint
-- Indexes: see the comments in src/db/schema.ts. They are created without
-- CONCURRENTLY because drizzle's migrator runs each migration in a
-- transaction, where CONCURRENTLY is not allowed, so CREATE INDEX blocks
-- writes to check_results while it builds. Fine at Beacon's size today. On a
-- table with hundreds of millions of rows, build the index by hand first with
-- CREATE INDEX CONCURRENTLY, and make the migration a no-op for it
-- (CREATE INDEX IF NOT EXISTS). Create the new index before dropping the old
-- one, so queries always have one.
CREATE INDEX "check_results_org_monitor_time_idx" ON "check_results" USING btree ("organization_id","monitor_id","checked_at","ok","latency_ms");--> statement-breakpoint
DROP INDEX "check_results_monitor_time_idx";--> statement-breakpoint
CREATE INDEX "incidents_open_idx" ON "incidents" USING btree ("monitor_id") WHERE "incidents"."resolved_at" is null;
