-- Lesson 2.2: the files table (metadata; the bytes live in object storage)
-- and the status page logo. Generated by drizzle-kit; the RLS policy at the
-- end is hand-written.
CREATE TYPE "public"."file_kind" AS ENUM('logo', 'incident_screenshot');--> statement-breakpoint
CREATE TYPE "public"."file_status" AS ENUM('pending', 'processing', 'ready', 'rejected');--> statement-breakpoint
CREATE TABLE "files" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"kind" "file_kind" NOT NULL,
	"incident_id" uuid,
	"key" text NOT NULL,
	"original_name" text NOT NULL,
	"declared_type" text NOT NULL,
	"declared_size" integer NOT NULL,
	"content_type" text,
	"size_bytes" integer,
	"status" "file_status" DEFAULT 'pending' NOT NULL,
	"rejection_reason" text,
	"thumbnail_key" text,
	"uploaded_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "files_key_unique" UNIQUE("key")
);
--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "logo_file_id" uuid;--> statement-breakpoint
ALTER TABLE "files" ADD CONSTRAINT "files_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "files" ADD CONSTRAINT "files_incident_id_incidents_id_fk" FOREIGN KEY ("incident_id") REFERENCES "public"."incidents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "files" ADD CONSTRAINT "files_uploaded_by_users_id_fk" FOREIGN KEY ("uploaded_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "files_org_created_idx" ON "files" USING btree ("organization_id","created_at");--> statement-breakpoint
CREATE INDEX "files_incident_idx" ON "files" USING btree ("incident_id");--> statement-breakpoint
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_logo_file_id_files_id_fk" FOREIGN KEY ("logo_file_id") REFERENCES "public"."files"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
-- Lesson 2.4: files carry organization_id, so they get the same row-level
-- security policy as the other tenant tables (0007). Added by hand below the
-- generated SQL; beacon_app's privileges on the new table come from 0007's
-- ALTER DEFAULT PRIVILEGES.
ALTER TABLE "files" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY tenant_isolation ON "files"
  USING (organization_id = current_org_id())
  WITH CHECK (organization_id = current_org_id());
