-- Lesson 2.3: search inside Postgres. Generated by drizzle-kit, plus
-- hand-written parts: the pg_trgm extension (first), a backfill, the
-- row-level security policy and the two search functions (last).
--
-- pg_trgm ships with Postgres. Since Postgres 13 it is a "trusted" extension,
-- so a database owner who is not a superuser (as on most managed providers)
-- may create it.
CREATE EXTENSION IF NOT EXISTS pg_trgm;--> statement-breakpoint
CREATE TABLE "incident_updates" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"incident_id" uuid NOT NULL,
	"author_id" uuid,
	"body" text NOT NULL,
	"search" "tsvector" GENERATED ALWAYS AS (to_tsvector('english', body)) STORED,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "incident_updates" ADD CONSTRAINT "incident_updates_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "incident_updates" ADD CONSTRAINT "incident_updates_incident_id_incidents_id_fk" FOREIGN KEY ("incident_id") REFERENCES "public"."incidents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "incident_updates" ADD CONSTRAINT "incident_updates_author_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "incident_updates_incident_idx" ON "incident_updates" USING btree ("incident_id","created_at");--> statement-breakpoint
CREATE INDEX "incident_updates_search_idx" ON "incident_updates" USING gin ("search");--> statement-breakpoint
CREATE INDEX "monitors_name_trgm_idx" ON "monitors" USING gin ("name" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "monitors_url_trgm_idx" ON "monitors" USING gin ("url" gin_trgm_ops);--> statement-breakpoint
-- Backfill: every existing incident gets its cause as a first update, so old
-- incidents are searchable too. New incidents get theirs from the check runner.
INSERT INTO "incident_updates" ("organization_id", "incident_id", "body", "created_at", "updated_at")
SELECT "organization_id", "id", 'Opened automatically: ' || "cause", "opened_at", "opened_at" FROM "incidents";--> statement-breakpoint
-- Lesson 2.4: a tenant table, so the same policy as the others (0007).
ALTER TABLE "incident_updates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY tenant_isolation ON "incident_updates"
  USING (organization_id = current_org_id())
  WITH CHECK (organization_id = current_org_id());--> statement-breakpoint
-- Where lessons 2.3 and 2.4 meet: row-level security switches off these
-- indexes. With RLS on, Postgres applies the policy before any condition
-- whose operator is not LEAKPROOF (one that could reveal a row's contents,
-- e.g. through an error message), and it cannot use such a condition to
-- search an index. The trigram operators (<%, ILIKE) and the full-text match
-- (@@) are not leakproof, so as beacon_app both searches read every row:
-- ~0.5 s instead of ~10 ms for 50,000 monitors.
--
-- The fix, recommended by Supabase for the same problem: a SECURITY DEFINER
-- function runs as its owner (the migration role, which RLS does not apply
-- to, see 0007), so the indexes work. The price: the function itself must
-- apply the tenant filter, and it does, from current_org_id(), the org that
-- withOrg() set. It takes no org argument, so a caller cannot point it at
-- another org, and without withOrg() it returns nothing.
-- SET search_path: a definer function must not look up objects in schemas a
-- caller controls. The pg_trgm threshold is set here too: its default (0.6)
-- misses one-letter typos in short words ("chekout" vs "checkout-api": 0.55).
CREATE FUNCTION search_monitors(q text, max_results int)
  RETURNS TABLE (id uuid, name text, url text, score real)
  LANGUAGE sql STABLE SECURITY DEFINER
  SET search_path = public, pg_temp
  SET pg_trgm.word_similarity_threshold = 0.4
AS $$
  WITH pattern AS (
    -- q matched literally by ILIKE: escape its own % and _ first.
    SELECT '%' || replace(replace(replace(q, '\', '\\'), '%', '\%'), '_', '\_') || '%' AS p
  )
  SELECT m.id, m.name, m.url, greatest(word_similarity(q, m.name), word_similarity(q, m.url)) AS score
  FROM monitors m, pattern
  WHERE m.organization_id = current_org_id()
    AND (q <% m.name OR q <% m.url OR m.name ILIKE pattern.p OR m.url ILIKE pattern.p)
  ORDER BY score DESC, m.name
  LIMIT max_results
$$;--> statement-breakpoint
CREATE FUNCTION search_incident_updates(q text, max_results int)
  RETURNS TABLE (update_id uuid, incident_id uuid, monitor_id uuid, monitor_name text,
                 opened_at timestamptz, resolved_at timestamptz, rank real, headline text)
  LANGUAGE sql STABLE SECURITY DEFINER
  SET search_path = public, pg_temp
AS $$
  SELECT u.id, i.id, m.id, m.name, i.opened_at, i.resolved_at,
         ts_rank(u.search, query) AS rank,
         -- Matches are wrapped in ⟦ ⟧, not HTML: see src/core/search.ts.
         ts_headline('english', u.body, query, 'StartSel=⟦, StopSel=⟧, MaxWords=25, MinWords=8, MaxFragments=2')
  FROM websearch_to_tsquery('english', q) AS query,
       incident_updates u
       JOIN incidents i ON i.id = u.incident_id AND i.organization_id = u.organization_id
       JOIN monitors m ON m.id = i.monitor_id AND m.organization_id = u.organization_id
  WHERE u.organization_id = current_org_id() AND u.search @@ query
  ORDER BY rank DESC, u.created_at DESC
  LIMIT max_results
$$;--> statement-breakpoint
-- Only the app role may call them (functions are callable by everyone by default).
REVOKE ALL ON FUNCTION search_monitors(text, int), search_incident_updates(text, int) FROM PUBLIC;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION search_monitors(text, int), search_incident_updates(text, int) TO beacon_app;
