-- Module 7: the staff table and impersonation sessions (lesson 7.1), and the
-- audit log (lesson 7.3). Generated by drizzle-kit from src/db/schema.ts; the
-- grants and the row-level security at the end are written by hand.
CREATE TYPE "public"."staff_role" AS ENUM('support', 'billing', 'engineer', 'superadmin');--> statement-breakpoint
CREATE TABLE "audit_events" (
	"id" uuid PRIMARY KEY NOT NULL,
	"seq" bigint GENERATED ALWAYS AS IDENTITY (sequence name "audit_events_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" uuid,
	"occurred_at" timestamp with time zone NOT NULL,
	"action" text NOT NULL,
	"category" text NOT NULL,
	"actor_type" text NOT NULL,
	"actor_id" text,
	"actor_name" text,
	"actor_email" text,
	"on_behalf_of_id" text,
	"on_behalf_of_name" text,
	"target_type" text,
	"target_id" text,
	"target_name" text,
	"ip_address" text,
	"user_agent" text,
	"request_id" text,
	"via" text,
	"reason" text,
	"changes" jsonb,
	"metadata" jsonb,
	"prev_hash" text NOT NULL,
	"hash" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "impersonation_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"token_hash" text NOT NULL,
	"staff_user_id" uuid NOT NULL,
	"target_user_id" uuid NOT NULL,
	"organization_id" uuid NOT NULL,
	"reason" text NOT NULL,
	"read_only" boolean DEFAULT true NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"ended_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "impersonation_sessions_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
CREATE TABLE "staff_users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"role" "staff_role" NOT NULL,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "staff_users_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "comp_plan" "plan_id";--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "comp_plan_until" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "subscriptions" ADD COLUMN "trial_end" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "impersonation_sessions" ADD CONSTRAINT "impersonation_sessions_staff_user_id_staff_users_id_fk" FOREIGN KEY ("staff_user_id") REFERENCES "public"."staff_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "impersonation_sessions" ADD CONSTRAINT "impersonation_sessions_target_user_id_users_id_fk" FOREIGN KEY ("target_user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "impersonation_sessions" ADD CONSTRAINT "impersonation_sessions_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "staff_users" ADD CONSTRAINT "staff_users_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "staff_users" ADD CONSTRAINT "staff_users_created_by_staff_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."staff_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_events_org_seq_idx" ON "audit_events" USING btree ("organization_id","seq");--> statement-breakpoint
CREATE INDEX "audit_events_org_category_seq_idx" ON "audit_events" USING btree ("organization_id","category","seq");--> statement-breakpoint
CREATE INDEX "audit_events_org_actor_seq_idx" ON "audit_events" USING btree ("organization_id","actor_id","seq");--> statement-breakpoint
CREATE INDEX "audit_events_org_target_seq_idx" ON "audit_events" USING btree ("organization_id","target_type","target_id","seq");--> statement-breakpoint
CREATE INDEX "audit_events_occurred_idx" ON "audit_events" USING btree ("occurred_at");--> statement-breakpoint
CREATE INDEX "impersonation_sessions_org_idx" ON "impersonation_sessions" USING btree ("organization_id","created_at");--> statement-breakpoint
CREATE INDEX "organizations_name_trgm_idx" ON "organizations" USING gin ("name" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "users_email_trgm_idx" ON "users" USING gin ("email" gin_trgm_ops);--> statement-breakpoint
-- Lesson 7.3: the audit log is tenant data, under row-level security like
-- every other tenant table: inside withOrg() an org sees and writes only its
-- own events. Platform events (organization_id NULL) match no org, so only
-- the owner role (staff pages, scripts) can read them.
ALTER TABLE "audit_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY tenant_isolation ON "audit_events"
  USING (organization_id = current_org_id())
  WITH CHECK (organization_id = current_org_id());--> statement-breakpoint
-- Append-only, enforced by the database and not by good intentions: the app
-- role may add events and read them, never change or delete one. (Retention
-- deletes run as the owner, in the worker's audit.retention job.)
REVOKE UPDATE, DELETE, TRUNCATE ON "audit_events" FROM beacon_app;--> statement-breakpoint
-- Lesson 7.1: the staff tables are never read inside a tenant transaction.
-- The app role gets nothing on them (least privilege; migration 0007 granted
-- every new table by default).
REVOKE ALL ON "staff_users", "impersonation_sessions" FROM beacon_app;