/**
 * Lesson 7.4 (self-hosting): `npm run env:docs` writes docs/configuration.md
 * from the configuration schema in src/lib/env.ts, so the list of variables a
 * self-hoster reads can never drift from what the app checks at startup.
 * `npm run env:docs -- --check` fails when the committed file is out of date (CI).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { envSchema } from '../src/lib/env';

const rows = Object.entries(envSchema.shape).map(([name, field]) => {
  const f = field as unknown as { description?: string; def?: { defaultValue?: unknown }; _zod: { def: { type: string; defaultValue?: unknown; innerType?: { _zod: { def: { type: string; entries?: Record<string, string> } } }; entries?: Record<string, string> } } };
  const def = f._zod.def;
  const inner = def.innerType?._zod.def;
  const values = def.entries ?? inner?.entries;
  const required = def.type !== 'optional' && def.type !== 'default';
  const defaultValue = def.type === 'default' ? String(typeof def.defaultValue === 'function' ? (def.defaultValue as () => unknown)() : def.defaultValue) : '';
  const allowed = values ? Object.values(values).map((v) => `\`${v}\``).join(', ') : '';
  return `| \`${name}\` | ${required ? 'yes' : 'no'} | ${defaultValue ? `\`${defaultValue}\`` : ''} | ${allowed} | ${(f.description ?? '').replace(/\|/g, '\\|')} |`;
});

const doc = `# Configuration

Generated by \`npm run env:docs\` from \`src/lib/env.ts\`: do not edit by hand. Every variable is read from
the environment (twelve-factor, lesson 7.4) and checked when the web app, the worker or the migrations start;
a missing or malformed one stops the process with a message that names it. "Required" also depends on the
rules at the bottom of the schema: \`BETTER_AUTH_SECRET\` in production, the \`S3_*\` values with
\`STORAGE_DRIVER=s3\`, the Stripe values together.

| Variable | Required | Default | Values | What it is |
|---|---|---|---|---|
${rows.join('\n')}
`;

const target = 'docs/configuration.md';
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== doc) {
    console.error(`${target} is out of date: run npm run env:docs`);
    process.exit(1);
  }
  console.log(`✓ ${target} is up to date`);
} else {
  writeFileSync(target, doc);
  console.log(`✓ wrote ${target} (${rows.length} variables)`);
}
